# KUC, PGR107
# HW4


## There are three tasks and should be finished and submitted through groups.
## Each group is suggested to have 1-5 members.
## In the submission, please include your implementation (executable code) as .ipynb document.
## List your group name and group member information in the top (written in comments).


### P4.1 Write a program to create two arrays of shape (2,2) and (2,1) respectively containing any number of integers. Concatenat the two arrays and then split it horizontally.

In [39]:
import numpy as np

a1 = np.array([2,3,4,5]).reshape((2,2))
print('first array (2,2):\n',a1)

a2 = np.array([22,33]).reshape((2,1))
print('seccond array (2,1):\n',a2)

print('Concatenat horizonaly:\n',np.concatenate((a1, a2), axis=1))


first array (2,2):
 [[2 3]
 [4 5]]
seccond array (2,1):
 [[22]
 [33]]
Concatenat horizonaly:
 [[ 2  3 22]
 [ 4  5 33]]


### P4.2 Give at least three examples along with their codes where broadcasting is not possible.

In [119]:
arr1 = np.array([3,4,1,14])

#arr2 = np.array([9,4,3])        #this doesnt work with arr2, arrays need to be in same shape/lenghth
#arr2 = np.array([9],[4],[3],3)  # this will not work, all is not in same dimention

#----------- need more examples


#this example will work, dimention doesn not matter as long as all is in same dimention
arr2 = np.array([[[9],[4],[3],[3]]])


multiplied = np.multiply(arr1,arr2)
print(arr1)
print(arr2)
print(multiplied)



[ 3  4  1 14]
[[[9]
  [4]
  [3]
  [3]]]
[[[ 27  36   9 126]
  [ 12  16   4  56]
  [  9  12   3  42]
  [  9  12   3  42]]]


### P4.3 Create two simple arrays a and b of any number of elements. Apply universal functions (refer to lecture slide#12) on the arguments, array a and array b.

In [98]:
def division(x,y):
    print(x,'divided by',y,'=',np.divide(x,y))
    
def multiply(x,y):
    print(x,'multiplied by',y,'=',np.multiply(x,y))

def addision(x,y):
    print(x,'added by',y,'=',np.add(x,y))
    
def substract(x,y):
    print(x,'substracted by',y,'=',np.subtract(x,y))

def powered(x,y):
    print(x,'powered by',y,'=',np.power(x,y))
    

a = np.array([3,6,9,12])
b = np.array([2,4,6,8])

division(a,6)
division(a,b)
multiply(b,2)
addision(b,3)
substract(a,3)
powered(b,2)

[ 3  6  9 12] divided by 6 = [0.5 1.  1.5 2. ]
[ 3  6  9 12] divided by [2 4 6 8] = [1.5 1.5 1.5 1.5]
[2 4 6 8] multiplied by 2 = [ 4  8 12 16]
[2 4 6 8] added by 3 = [ 5  7  9 11]
[ 3  6  9 12] substracted by 3 = [0 3 6 9]
[2 4 6 8] powered by 2 = [ 4 16 36 64]
